export default [
    {id:1, 
    year_of_made:"09.06.1994", 
    end_date:"09.06.2021", 
    tag: ["Japanese"],
    title: "Honda",
    description: "Some text",  
    price: 100000, 
    is_done: true,
    masters: ["Ivan"," Alex"],
    path: "/images/honda.webp"},

    {id:2, 
    year_of_made:"01.01.1977", 
    end_date:"03.05.2022", 
    tag: ["America"],
    title: "Harley Davidson",
    description: "Some text",  
    price: 200000, 
    is_done: true,
    masters: ["Maksim ","Zoy ","Leon" ],
    path: "/images/Harley_davidson.jpeg"},

    {id:3, 
    year_of_made:"09.05.1945", 
    end_date:"11.10.2026", 
    tag: ["Germany"],
    title: "BMW",
    description: "Some text",  
    price: 300000, 
    is_done: false,
    masters: ["Zoy ","Leon "],
    path: "/images/BMW.jpeg"},

    {id:4, 
    year_of_made: "19.11.1980",
    end_date:"01.01.2024",
    tag: ["Britan"],
    title: "Triumph",
    description: "Some text",  
    price: 40000, 
    is_done: true,
    masters: ["Ivan ","Leon " ],
    path: "/images/Triumph.jpg"},

    {id:5, 
    year_of_made:"04.03.1964", 
    end_date:"21.09.2024", 
    tag: ["USSR"],
    title: "Ural",
    description: "Some text",  
    price: 500000, 
    is_done: false,
    masters: ["Maksim "],
    path: "/images/URAL.jpg"},
]

